server:
  port: 8080

spring:
  application:
    name: consumer2.0

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8086/eureka,http://${eureka.instance.hostname}:8087/eureka

      
password: '{cipher}204f64c5e7ddd50aa3b1140d93b29720e4544c407b520bfca9a00bf7703ae491'
