server:
  port: 8083

spring:
  application:
    name: consumer

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8086/eureka,http://${eureka.instance.hostname}:8087/eureka
